### ISSUE TITLE
What's the definition of different levels?

### ISSUE THREAD

**Issue by HelixNGC7293** [HighCWu/anime_biggan_toy#4]
I noticed that the pic can only be changed by shape or color during interpolation, controlled by levels.
If it's possible, is there any definition of these levels (e.g. z11; z32; z42...)
Thank you so much!

example code in sample.ipynb:
std_gen_interpolate(8, seed=2333, out_path='data/std_inter1', levels="z11;z12")
std_gen_interpolate(8, seed=2333, out_path='data/std_inter2', levels="z21;z22")
std_gen_interpolate(8, seed=2333, out_path='data/std_inter3', levels="z31;z32")
std_gen_interpolate(8, seed=2333, out_path='data/std_inter4', levels="z41;z42")
std_gen_interpolate(8, seed=2333, out_path='data/std_inter5', levels="z51;z52")
std_gen_interpolate(8, seed=2333, out_path='data/std_inter6', levels="z61;z62")

**Comment by HighCWu** [comment]
这些级别没有准确的有含义的定义，因为这些相当于神经网络自己学习到的内容。通过简单联想的话，可以大致明白神经网络各级别的表现的缘由。就像人绘画一样，从最底层的级别开始往上，先确定绘画的大致形态，然后拿黑色笔刷加上一些深浅，再细化细节，最后再上色。不过神经网络自己可能分得更细一些。
There is no precise and meaningful definition of these levels, because these are equivalent to what the neural network has learned.  Through simple association, you can roughly understand the reason for the performance of the neural network at each level.  Just like a human painting, starting from the bottom level and going up, first determine the general form of the painting, then use a black brush to add some shades, then refine the details, and finally colorize it. However, the neural network itself may do it more detailed.

**Comment by HelixNGC7293** [comment]
原来如此！我研究一下~
Thank you again!~
